//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hepsiburada_Seller_Information.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seller_Information
    {
        public long ID { get; set; }
        public string Link { get; set; }
        public string StoreName { get; set; }
        public string Telephone { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string Fax { get; set; }
        public string Mersis { get; set; }
        public string Category { get; set; }
        public Nullable<decimal> StoreScore { get; set; }
        public Nullable<int> NumberOfRatings { get; set; }
        public Nullable<int> NumberOfFollowers { get; set; }
        public string AverageDeliveryTime { get; set; }
        public string ResponseTime { get; set; }
        public Nullable<decimal> RatingScore { get; set; }
        public Nullable<int> NumberOfComments { get; set; }
        public Nullable<bool> FastSaller { get; set; }
        public Nullable<int> NumberOfProducts { get; set; }
        public string SellerName { get; set; }
        public string VKN { get; set; }
    }
}
